# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-29 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='college',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_name', models.CharField(max_length=50)),
                ('college_details', models.TextField()),
                ('college_rating', models.CharField(max_length=15)),
            ],
        ),
    ]
